drop schema IF EXISTS SalesLeads;

create schema IF NOT EXISTS SALESLEADS;

drop table IF EXISTS SALESLEADS.SALESLEADS;

create table IF NOT EXISTS SALESLEADS.SALESLEADS (
    ID VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONENUMBER VARCHAR(255)
);

