
drop table IF EXISTS SalesLeads;

create table IF NOT EXISTS SALESLEADS (
    ID VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONENUMBER VARCHAR(255)
);


--NUMBER AUTO_INCREMENT,
